name: Push to Docker Hub and Deploy to Azure Container

on:
  push:
    branches:
      [ development ]

  workflow_dispatch:

# TODO: Run MyPy check and tests

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.VITAAPITEST_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry and deploy to Azure container
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: docker.io
          registryUsername: ${{ secrets.VITAAPITEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VITAAPITEST_REGISTRY_PASSWORD }}
          containerAppName: vita-api-test
          resourceGroup: vitaapitest
          imageToBuild: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}:dev
          

     

