name: Publish Docker Image

on:
  push:
    branches:
      - production
      - development

jobs:
  Build-x86:
    name: Build ${{ matrix.service }} (x86)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ 'vita-api', 'vita-mcp', 'apollo', 'chronos' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:${{ github.ref_name == 'production' && 'latest' || 'dev' }}
          platforms: linux/amd64
          file: ./${{ matrix.service }}/Dockerfile

  Build-ARM:
    name: Build ${{ matrix.service }} (ARM)
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        service: [ 'vita-api', 'vita-mcp', 'apollo', 'chronos' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:${{ github.ref_name == 'production' && 'latest' || 'dev' }}
          platforms: linux/arm64
          file: ./${{ matrix.service }}/Dockerfile